"""PySide6 bindings for the Scintilla code editor component.

Re-exports the public API of the compiled ``_pyside6_scintilla`` extension
module, which is generated by shiboken6 from
``src/pyside6_scintilla/bindings/bindings.xml``. See ``docs/bindings.md`` for
how the bindings are built and maintained.
"""

# the binding will not load if we don't explicitly import PySide6.QtWidgets
import PySide6.QtWidgets  # noqa: F401

from ._pyside6_scintilla import (
    Scintilla,
    ScintillaDocument,
    ScintillaEdit,
    ScintillaEditBase,
)

__version__ = "5.6.3.1"

__all__ = [
    "Scintilla",
    "ScintillaDocument",
    "ScintillaEdit",
    "ScintillaEditBase",
    "__version__",
]
